version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: sudo apt-get install libudev-dev libusb-1.0-0-dev
      - run:
          name: build
          command: |
            rustc --version
            cargo --version
            cargo build
      - run:
          name: build --release
          command: |
            rustc --version
            cargo --version
            cargo build --release

  checks:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: sudo apt-get install libudev-dev libusb-1.0-0-dev
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo install --force cargo-audit
      - run:
          name: rustfmt
          command: |
            cargo fmt --version
            cargo fmt -- --check
      - run:
          name: clippy
          command: |
            cargo clippy --version
            cargo clippy --all-features
      - run:
          name: audit
          command: |
            cargo audit --version
            cargo audit

  tests:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: sudo apt-get install libudev-dev libusb-1.0-0-dev
      - run:
          name: test --all-features
          command: |
            rustc --version
            cargo --version
            cargo test --all --all-features -- --test-threads 1

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - checks
#      - tests
